# Generated by Django 5.1.1 on 2024-09-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('n_convenio', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mill Finish', 'Mill Finish'), ('Silver Anodized (FAYP01)', 'Silver Anodized (FAYP01)'), ('White Powder Coat', 'White Powder Coat'), ('Bronze Anodized (FAYP03)', 'Bronze Anodized (FAYP03)'), ('Black Anodized (FAYP06)', 'Black Anodized (FAYP06)'), ('Elect. Champagne (FAYH02)', 'Elect. Champagne (FAYH02)'), ('Wood Finish (FA2134-1)', 'Wood Finish (FA2134-1)'), ('Wood Finish (Light)', 'Wood Finish (Light)'), ('Rust Finish', 'Rust Finish')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('ie', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='PedidoAPP.agent')),
                ('factories', models.ManyToManyField(to='PedidoAPP.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(blank=True, max_length=255, null=True)),
                ('n_containers', models.PositiveIntegerField(blank=True, default=0)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('percentage_under250', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PedidoAPP.company')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PedidoAPP.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumifont_code', models.CharField(max_length=50, unique=True)),
                ('ncm', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('length_mm', models.DecimalField(decimal_places=2, default=6000, max_digits=10)),
                ('temper_alloy', models.CharField(default='6063T5', max_length=50)),
                ('enabled_companies', models.ManyToManyField(blank=True, related_name='enabled_products', to='PedidoAPP.company')),
                ('surface_finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='PedidoAPP.surfacefinish')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_code', models.CharField(max_length=50)),
                ('weight_m_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_products', to='PedidoAPP.factory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_products', to='PedidoAPP.product')),
            ],
            options={
                'unique_together': {('factory', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='PedidoAPP.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='PedidoAPP.factoryproduct')),
                ('surface_finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='PedidoAPP.surfacefinish')),
            ],
            options={
                'unique_together': {('order', 'product', 'surface_finish')},
            },
        ),
    ]
