# Generated by Django 5.1.1 on 2024-09-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('n_convenio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumifont_code', models.CharField(max_length=50, unique=True)),
                ('factory_code', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('length_mm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temper_alloy', models.CharField(max_length=50)),
                ('weight_m_kg', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SurfaceFinish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mill Finish', 'Mill Finish'), ('Silver Anodized (FAYP01)', 'Silver Anodized (FAYP01)'), ('White Powder Coat', 'White Powder Coat'), ('Bronze Anodized (FAYP03)', 'Bronze Anodized (FAYP03)'), ('Black Anodized (FAYP06)', 'Black Anodized (FAYP06)'), ('Elect. Champagne (FAYH02)', 'Elect. Champagne (FAYH02)'), ('Wood Finish (FA2134-1)', 'Wood Finish (FA2134-1)'), ('Wood Finish (Light)', 'Wood Finish (Light)'), ('Rust Finish', 'Rust Finish')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('ie', models.CharField(max_length=20, unique=True)),
                ('factory', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='PedidoAPP.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=255)),
                ('n_containers', models.PositiveIntegerField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage_under250', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('products', models.ManyToManyField(related_name='orders', to='PedidoAPP.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='surface_finish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='PedidoAPP.surfacefinish'),
        ),
    ]
