# Generated by Django 5.1.1 on 2024-09-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
