# Generated by Django 5.1.1 on 2024-09-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='n_containers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='percentage_under250',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
