# Generated by Django 5.1.1 on 2024-09-10 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='surface_finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='PedidoAPP.surfacefinish'),
        ),
    ]
