# Generated by Django 5.1.1 on 2024-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoAPP', '0002_alter_product_length_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='typeCompany',
            field=models.IntegerField(default=1),
        ),
    ]
