# Generated by Django 5.1.1 on 2024-09-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoAPP', '0003_remove_surfacefinish_amount_alter_order_n_containers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
