# Generated by Django 5.1.1 on 2024-09-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PedidoAPP', '0004_alter_surfacefinish_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='custom_length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
